name: quickshop
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

# Manually increment using semver approach when performing a release:
# - Increment major version for substantial app changes
# - Increment minor version for standard releases / new features
# - Increment patch version for bug fixes
# Ensure to add an entry in CHANGELOG.md for each release describing the changes.
version: 0.1.6

environment:
  sdk: ^3.5.4

dependencies:
  cloud_firestore: ^5.4.5
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  firebase_ui_auth: ^1.16.0
  firebase_ui_oauth_google: ^1.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed_annotation: ^2.4.4
  go_router: ^14.3.0
  google_sign_in: ^6.2.1
  http: ^1.2.2
  json_annotation: ^4.9.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  sentry_flutter: ^8.9.0
  share_plus: ^10.1.2
  shared_preferences: ^2.3.2
  skeletonizer: ^1.4.2
  sqflite: ^2.4.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1
  riverpod_generator: ^2.6.2
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  fonts:
    - family: RacingSansOne
      fonts:
        - asset: assets/fonts/RacingSansOne-Regular.ttf

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/logo/
    - assets/fonts/
